Output assets/interactive2.gif
Set CursorBlink false
Set FontSize 16
Set Framerate 20
Set Height 900
Set Margin 0
Set PlaybackSpeed 1.0
Set Shell zsh
Set Theme "iTerm2 Default"
Set TypingSpeed 80ms
Set Width 1500

Type "csvs -i MOCK_DATA2.csv"
Sleep 500ms
Enter
Sleep 500ms
Enter
Sleep 500ms
Tab
Sleep 500ms
Ctrl+X
Sleep 500ms
Tab
Sleep 500ms
Tab
Ctrl+T
Down 2
Screenshot assets/interactive2.banner.png
Ctrl+C
