name: Release

permissions:
  contents: write

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release - ${{ matrix.platform.os }} ${{ matrix.platform.arch }}-${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}-latest
    strategy:
      matrix:
        platform:
          - os: linux
            arch: aarch64
            target: unknown-linux-musl
            executable: csvs
          - os: linux
            arch: x86_64
            target: unknown-linux-musl            
            executable: csvs
          - os: macos
            arch: aarch64
            target: apple-darwin            
            executable: csvs
          - os: macos
            arch: x86_64
            target: apple-darwin          
            executable: csvs
          - os: windows
            arch: aarch64
            target: pc-windows-msvc          
            executable: csvs.exe
          - os: windows
            arch: x86_64
            target: pc-windows-msvc          
            executable: csvs.exe
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --target ${{ matrix.platform.arch }}-${{ matrix.platform.target }} --target-dir target-${{ matrix.platform.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: csvs_${{ matrix.platform.os }}_${{ matrix.platform.arch }}
          path: |
            target-${{ matrix.platform.os }}/${{ matrix.platform.arch }}-${{ matrix.platform.target }}/release/${{ matrix.platform.executable }}
            *.md
            LICENSE
