name: Release

permissions:
  contents: write

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release - ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}-latest
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-musl
            executable: csvs
            artifact: csvs_linux_aarch64
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl            
            executable: csvs
            artifact: csvs_linux_x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin            
            executable: csvs
            artifact: csvs_macos_aarch64
          - runner: macos-latest
            target: x86_64-apple-darwin          
            executable: csvs
            artifact: csvs_macos_x86_64
          - runner: windows-latest
            target: aarch64-pc-windows-msvc          
            executable: csvs.exe
            artifact: csvs_windows_aarch64
          - runner: windows-latest
            target: x86_64-pc-windows-msvc          
            executable: csvs.exe
            artifact: csvs_windows_x86_64
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.platform.target }}
      - run: cargo build --release --target ${{ matrix.platform.target }} --target-dir ${{ matrix.platform.runner }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact }}
          path: |
            ${{ matrix.platform.runner }}/${{ matrix.platform.target }}/release/${{ matrix.platform.executable }}
            *.md
            LICENSE
